### PR TITLE
Adds geojson file for Indian State boundaries

### PR DESCRIPTION
**Pull request by rasagy**
Created from the shape files already present in the repo, using [MapShaper](http://mapshaper.org/).

### CODE REVIEW

**Comment by devdattaT** [comment]
@rasagy , what exact changes are made in this PR to the states GeoJSON?

**Comment by rasagy** [comment]
Sorry for the double commit — the first commit was a slightly simplified geojson file that I had used, but then I replaced that with the original geojson that MapShaper exports from your shapefile.

**Comment by devdattaT** [comment]
So this is just the States Boundary in GeoJSON format, right?

I'm weary of keeping the same data in multiple formats, because of two reasons:

1. It makes the Repo heavy. Right now this Repo is already 60 Mb, and adding a 13 MB File for redundant data is unnecessary (IMHO)

2. Updating Information could be problematic in the future, because these kinds of things could easily get out of sync.

I think it's better to give instructions to users who want to convert the data to different formats,  rather than adding this converted data.

**Comment by rasagy** [comment]
Ah right, I didn't know about this approach, but it definitely makes sense.
The details on how to convert this to geojson are anyway in the repo readme, so I'll close this PR.

Thanks for the prompt replies! 🙇

**Pull request closed without merging**
